// AUTO-GENERATED by scripts/sync-prompts.ts. Do not edit by hand.

import { listingCopywriterPrompt } from "./listing-copywriter.ts";
import { weeklyReportPrompt } from "./weekly-report.ts";
import { listingPrepPrompt } from "./listing-prep.ts";
import { marketRentAnalysisPrompt } from "./market-rent-analysis.ts";
import { edgeCasePrompt } from "./edge-case.ts";
import { meetAsterPrompt } from "./meet-aster.ts";
import { incidentReportPrompt } from "./incident-report.ts";
import { decisionToRolloutPrompt } from "./decision-to-rollout.ts";
import { shoutOutPrompt } from "./shout-out.ts";
import { speedToLeadPrompt } from "./speed-to-lead.ts";
import { screeningPrompt } from "./screening.ts";
import { noDramaPrompt } from "./no-drama.ts";

export { listingCopywriterPrompt };
export { weeklyReportPrompt };
export { listingPrepPrompt };
export { marketRentAnalysisPrompt };
export { edgeCasePrompt };
export { meetAsterPrompt };
export { incidentReportPrompt };
export { decisionToRolloutPrompt };
export { shoutOutPrompt };
export { speedToLeadPrompt };
export { screeningPrompt };
export { noDramaPrompt };

export const ALL_PROMPTS = [
  listingCopywriterPrompt,
  weeklyReportPrompt,
  listingPrepPrompt,
  marketRentAnalysisPrompt,
  edgeCasePrompt,
  meetAsterPrompt,
  incidentReportPrompt,
  decisionToRolloutPrompt,
  shoutOutPrompt,
  speedToLeadPrompt,
  screeningPrompt,
  noDramaPrompt,
];
