// AUTO-GENERATED by scripts/sync-prompts.ts. Do not edit by hand.

import { listingCopywriterPrompt } from "./listing-copywriter.ts";
import { listingPrepPrompt } from "./listing-prep.ts";
import { marketRentAnalysisPrompt } from "./market-rent-analysis.ts";
import { edgeCasePrompt } from "./edge-case.ts";
import { weeklyLeasingReportPrompt } from "./weekly-leasing-report.ts";
import { meetAsterPrompt } from "./meet-aster.ts";
import { incidentReportPrompt } from "./incident-report.ts";
import { decisionToRolloutPrompt } from "./decision-to-rollout.ts";
import { shoutOutPrompt } from "./shout-out.ts";

export { listingCopywriterPrompt };
export { listingPrepPrompt };
export { marketRentAnalysisPrompt };
export { edgeCasePrompt };
export { weeklyLeasingReportPrompt };
export { meetAsterPrompt };
export { incidentReportPrompt };
export { decisionToRolloutPrompt };
export { shoutOutPrompt };

export const ALL_PROMPTS = [
  listingCopywriterPrompt,
  listingPrepPrompt,
  marketRentAnalysisPrompt,
  edgeCasePrompt,
  weeklyLeasingReportPrompt,
  meetAsterPrompt,
  incidentReportPrompt,
  decisionToRolloutPrompt,
  shoutOutPrompt,
];
