// AUTO-GENERATED by scripts/sync-prompts.ts. Do not edit by hand.

import { edgeCasePrompt } from "./edge-case.ts";
import { weeklyLeasingReportPrompt } from "./weekly-leasing-report.ts";
import { meetAsterPrompt } from "./meet-aster.ts";
import { incidentReportPrompt } from "./incident-report.ts";
import { decisionToRolloutPrompt } from "./decision-to-rollout.ts";
import { shoutOutPrompt } from "./shout-out.ts";

export { edgeCasePrompt };
export { weeklyLeasingReportPrompt };
export { meetAsterPrompt };
export { incidentReportPrompt };
export { decisionToRolloutPrompt };
export { shoutOutPrompt };

export const ALL_PROMPTS = [
  edgeCasePrompt,
  weeklyLeasingReportPrompt,
  meetAsterPrompt,
  incidentReportPrompt,
  decisionToRolloutPrompt,
  shoutOutPrompt,
];
