// AUTO-GENERATED from skills/market-rent-analysis/SKILL.md by scripts/sync-prompts.ts
// Do not edit this file by hand. Edit the SKILL.md, then re-run sync-prompts.

export const marketRentAnalysisPrompt = {
  name: "market-rent-analysis",
  description: "Establishes a defensible market rent recommendation from 3 Zillow comparable listings for a Sagareus rental property. Extracts rent, days on market, move-in costs, and concessions from each comp. Calculates target rent using price-per-square-foot averaging. Flags quality concerns (long DOM, heavy concessions, size mismatches). Outputs a per-comp summary, the calculation, and the recommended rent (rounded to nearest $25). Note that the agent typically picks a starting rent $100 to $200 above this recommendation. Use when the agent says \"what should I list this at,\" \"run comp analysis on these URLs,\" \"market rent recommendation for [property],\" or invokes /market-rent-analysis. Also invoked by /listing-prep as a sub-skill.",
  content: `# Market Rent Analysis — comp analysis skill

## What this is

Establishes a defensible market rent number from three Zillow comparable listings. The output is what the agent uses to anchor the listing price decision, plus what gets pasted into the PreListing email for the owner to see.

The recommendation is a single number rounded to the nearest $25. The agent typically picks a **starting rent $100 to $200 above** this recommendation to test demand.

## When to use

- Agent invokes \`/market-rent-analysis\`
- Agent says "what should I list this at," "run comp analysis on these URLs," "market rent recommendation for [property]," "price check on [address]," or similar
- Called by \`/listing-prep\` orchestrator as part of the full prelisting workflow

## When NOT to use

- Agent wants listing copy → use \`/listing-copywriter\`
- Agent wants the full prelisting bundle → use \`/listing-prep\`
- Comp question is conceptual ("how do we generally think about market rent?") → answer directly without running the skill

## Inputs

**Required:**
- Three Zillow comparable listing URLs
- Subject property:
  - Address
  - Beds, baths, sqft
  - Condition notes
  - Key amenities

**Optional:**
- Current rent in Buildium (helps with year-over-year comparison)
- Date the unit was last leased and the rate at that time

## Conceptual framing — what market rent is

Market rent is what a qualified resident is willing to pay in the open market based on current supply and demand. Key factors that move it:

- **Comparable properties:** size, condition, amenities, location
- **Location and neighborhood trends:** jobs, transit, schools, walkability
- **Unit condition and upgrades:** new flooring, fresh paint, modern appliances
- **Timing and seasonality:** rents typically run higher in spring and summer
- **Vacancy rates and demand:** soft market means more concessions, longer DOM
- **Incentives and concessions:** affect effective rent, not just the headline number

A comp analysis is one data point, not a final answer. The agent uses it as the anchor and adjusts based on Sagareus-specific knowledge of the property and the owner's situation.

## Workflow

### Step 1: fetch and extract from each Zillow comp

For each of the 3 URLs, extract:

- Address (or neighborhood if address is hidden)
- Asking rent
- Beds, baths, sqft
- Days on market
- Move-in costs: security deposit, fees, last month's rent if listed
- Concessions or move-in specials (e.g., "$500 off first month," "1 month free")
- Key amenities

**Important:** inquiry counts and showing activity are NOT publicly visible on Zillow. Do not invent these numbers. If asked, mark as "not publicly available."

**If a Zillow fetch fails** (404, paywall, listing pulled, JS-rendered, anti-bot block, etc.), surface which URL(s) failed and ask the agent to paste the relevant details:

\`\`\`
Comp 2 didn't fetch. Paste these details and I'll continue:
  • Address / neighborhood
  • Asking rent
  • Beds, baths, sqft
  • Days on market
  • Move-in costs (security deposit, last month, fees)
  • Concessions
  • Key amenities
\`\`\`

Don't guess.

### Step 2: internal data cross-reference (only if provided)

If the agent gave the current Buildium rent and / or the last leased rate:

- Compare current Buildium rent to comp rents
- Evaluate the proposed percentage increase against comp movement
- Flag if proposed increase exceeds comp movement without condition-based justification

Example flag: "Comps moved roughly 5% year over year, but the proposed Buildium increase is 10%. Justify with condition upgrades (new flooring, paint, etc.) or revisit the number."

Skip this step entirely if the agent didn't provide internal data.

### Step 3: price-per-square-foot calculation

Formula:

\`\`\`
(Comp1 $/sf + Comp2 $/sf + Comp3 $/sf) / 3  ×  Subject sf  =  Target Rent
\`\`\`

**Show the calculation explicitly** in the output. Round the final number to the nearest $25.

Example:

\`\`\`
Comp 1: $2,400 / 850 sf = $2.82/sf
Comp 2: $2,650 / 950 sf = $2.79/sf
Comp 3: $2,500 / 880 sf = $2.84/sf

Average $/sf: ($2.82 + $2.79 + $2.84) / 3 = $2.82/sf
Subject sqft: 900
Target rent: $2.82 × 900 = $2,538 → rounded to $2,550
\`\`\`

### Step 4: flag quality concerns

Look at the comps and the calculation for anything that weakens the recommendation. Surface each flag plainly.

Common flags:

- **Long days on market on comps** (>21 days) → possible overpricing in the area, soft demand. Consider a lower starting rent.
- **Heavy concessions** ($1K+ rent credits, 1 month free) → soft demand. Effective rent is lower than the headline.
- **Significant size mismatch** (comps 30%+ off subject sqft) → unreliable, recommend the agent find better comps.
- **Bed/bath mismatch** → same, unreliable.
- **Stale comps** (DOM 60+) → likely overpriced or off-market, don't weight heavily.
- **One outlier comp** with rent 20%+ above or below the other two → flag it, suggest the agent decide whether to keep or replace.

If there are no flags, say so: "No quality concerns. Comps are well-matched and recently active."

### Step 5: output

Return all of:

**1. Per-comp summary table:**

\`\`\`
Comp 1: [address/neighborhood]
  Rent: $X,XXX
  Beds / Baths / Sqft: X / X / XXX
  Days on market: XX
  Total move-in cost: $X,XXX
  Concessions: [details or "none"]
  URL: [Zillow link]

Comp 2: [...]

Comp 3: [...]
\`\`\`

**2. Subject property recap:**

\`\`\`
Subject: [address]
  Beds / Baths / Sqft: X / X / XXX
  Condition: [notes]
  Key amenities: [list]
\`\`\`

**3. Calculation:** the price-per-square-foot math, shown explicitly.

**4. Recommended market rent:** a single number, rounded to nearest $25.

**5. Quality flags:** any concerns from Step 4, or "no quality concerns" if none.

**6. Note on starting rent:**

\`\`\`
Starting rent for the listing is typically $100 to $200 above this
market rent figure, picked by you based on the property and the
owner's situation. The market rent above is the anchor, not the
listing price.
\`\`\`

## Voice rules

- **Never use em dashes.** Commas, semicolons, periods.
- Plain English. No corporate jargon.
- Numbers are concrete and shown explicitly. No vague "around $2,500."
- Flags are direct, not hedged. If something is off, say so.

## Edge cases

- **Agent gives only 1 or 2 URLs:** ask for the third. If they can't find a third, accept it but note: "two comps is the floor, three is the minimum for the SOP. Flagging this for the owner's awareness."
- **All three comps are way off-size:** run the calculation but flag heavily. Recommend the agent re-pull comps.
- **Comps are in different neighborhoods:** flag it if the rent ranges differ significantly. Neighborhood matters more than square footage in some submarkets.
- **One comp is the same property** (e.g., they accidentally pasted the subject's URL): catch it, ask for a replacement.
- **Comps are commercial or sale listings, not rentals:** catch the URL type, ask for rental comps.

## Out of scope

- Setting the starting rent. That's the agent's call, $100 to $200 above the recommendation by default but they decide.
- Suggesting strategies to drive activity. That's \`/weekly-report\`.
- Pulling Rentometer data. SOP mentions it but v0 of this skill is Zillow-only.
- Posting the analysis to Asana. That happens in \`/listing-prep\` for the orchestrator flow.

## Limitations to flag if asked

- v0. Zillow data is fetched live but their layout can change. Verify the rent and DOM look right before pasting into the owner email.
- Inquiry counts and showing activity are NOT publicly available on Zillow.
- One data point. The recommendation anchors the decision, doesn't replace the agent's judgment.
- No Rentometer integration yet. SOP mentions cross-referencing with Rentometer, that's a future enhancement.`,
};
