// Ask Aster — sync-prompts script
//
// Reads SKILL.md files from skills/<name>/SKILL.md, parses YAML frontmatter
// (name + description), and generates TypeScript prompt modules at
// supabase/functions/ask-aster/prompts/<name>.ts.
//
// SKILL.md is the source of truth for prompt content. The generated TS files
// are deployment artifacts — do not edit them by hand.
//
// Run from the repo root:
//   deno run --allow-read --allow-write scripts/sync-prompts.ts
//
// Pre-deploy hook:
//   deno run --allow-read --allow-write scripts/sync-prompts.ts \
//     && supabase functions deploy ask-aster

import { walk } from "jsr:@std/fs/walk";
import { dirname, fromFileUrl, join, relative } from "jsr:@std/path";

const REPO_ROOT = dirname(dirname(fromFileUrl(import.meta.url)));
const SKILLS_DIR = join(REPO_ROOT, "skills");
const PROMPTS_DIR = join(
  REPO_ROOT,
  "supabase",
  "functions",
  "ask-aster",
  "prompts",
);

// --- frontmatter parser (minimal — just `name:` and `description:`) ---

function parseFrontmatter(md: string): {
  frontmatter: Record<string, string>;
  body: string;
} {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!m) {
    throw new Error("SKILL.md missing YAML frontmatter delimited by ---");
  }
  const fmRaw = m[1];
  const body = m[2];
  const frontmatter: Record<string, string> = {};
  // Simple line-based parser: handle "key: value" and continuation lines that
  // start with whitespace (folded scalars). We don't need full YAML — just
  // name and description.
  let currentKey: string | null = null;
  for (const line of fmRaw.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const kv = line.match(/^([a-zA-Z_][a-zA-Z0-9_-]*):\s*(.*)$/);
    if (kv && !line.startsWith(" ") && !line.startsWith("\t")) {
      currentKey = kv[1];
      frontmatter[currentKey] = kv[2];
    } else if (currentKey) {
      // Continuation of previous value (folded scalar)
      frontmatter[currentKey] = (frontmatter[currentKey] + " " + line.trim()).trim();
    }
  }
  return { frontmatter, body };
}

// --- TS string literal escaper ---

function toTsTemplateLiteral(s: string): string {
  // Escape backticks, backslashes, and `${` interpolation triggers so the body
  // can sit inside a TypeScript template literal verbatim.
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

// --- generator ---

function generateTs(name: string, description: string, body: string): string {
  const safeBody = toTsTemplateLiteral(body);
  const safeDesc = description.replace(/"/g, '\\"');
  return `// AUTO-GENERATED from skills/${name}/SKILL.md by scripts/sync-prompts.ts
// Do not edit this file by hand. Edit the SKILL.md, then re-run sync-prompts.

export const ${camelCase(name)}Prompt = {
  name: "${name}",
  description: "${safeDesc}",
  content: \`${safeBody}\`,
};
`;
}

function camelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// --- main ---

async function main() {
  // Find all SKILL.md files under skills/
  const skillFiles: string[] = [];
  for await (
    const entry of walk(SKILLS_DIR, {
      includeDirs: false,
      match: [/SKILL\.md$/],
    })
  ) {
    skillFiles.push(entry.path);
  }

  if (skillFiles.length === 0) {
    console.error(`No SKILL.md files found under ${SKILLS_DIR}`);
    Deno.exit(1);
  }

  await Deno.mkdir(PROMPTS_DIR, { recursive: true });

  const generated: string[] = [];
  for (const filePath of skillFiles) {
    const md = await Deno.readTextFile(filePath);
    const { frontmatter, body } = parseFrontmatter(md);
    const name = frontmatter.name;
    const description = frontmatter.description;
    if (!name || !description) {
      console.error(
        `Skipping ${relative(REPO_ROOT, filePath)} — missing name or description in frontmatter`,
      );
      continue;
    }

    // Bundle supporting .md files in the same skill folder into the deployed
    // prompt. The MCP runtime is a single text body — no file system — so any
    // "Read SCREENING_CRITERIA.md in this skill's folder" instruction in the
    // SKILL.md only works if the file content travels with the prompt.
    // Scan only the immediate skill directory; subfolders (e.g. examples/)
    // are excluded on purpose since they are reference material, not runtime.
    const skillDir = dirname(filePath);
    const supporting: { name: string; content: string }[] = [];
    for await (const entry of Deno.readDir(skillDir)) {
      if (
        entry.isFile &&
        entry.name.endsWith(".md") &&
        entry.name !== "SKILL.md"
      ) {
        supporting.push({
          name: entry.name,
          content: (await Deno.readTextFile(join(skillDir, entry.name))).trim(),
        });
      }
    }
    supporting.sort((a, b) => a.name.localeCompare(b.name));

    let bundledBody = body.trim();
    if (supporting.length > 0) {
      const parts = [
        bundledBody,
        "",
        "---",
        "",
        "# Skill folder files",
        "",
        "These files were bundled into this prompt at deploy time. The MCP runtime serves a single text body and does not expose a file system. When the instructions above reference a filename in this skill's folder, find the file's content below.",
      ];
      for (const f of supporting) {
        parts.push("", `## ${f.name}`, "", f.content);
      }
      bundledBody = parts.join("\n");
    }

    const ts = generateTs(name, description, bundledBody);
    const outPath = join(PROMPTS_DIR, `${name}.ts`);
    await Deno.writeTextFile(outPath, ts);
    generated.push(name);
    const bundleNote = supporting.length > 0
      ? ` (+${supporting.length} bundled file(s): ${supporting.map((f) => f.name).join(", ")})`
      : "";
    console.log(
      `Wrote ${relative(REPO_ROOT, outPath)} (${bundledBody.length} chars)${bundleNote}`,
    );
  }

  // Write an index.ts that re-exports everything, so the function can do a
  // single import.
  const indexLines = [
    `// AUTO-GENERATED by scripts/sync-prompts.ts. Do not edit by hand.`,
    ``,
    ...generated.map((n) => `export { ${camelCase(n)}Prompt } from "./${n}.ts";`),
    ``,
    `export const ALL_PROMPTS = [`,
    ...generated.map((n) => `  ${camelCase(n)}Prompt,`),
    `];`,
  ];
  // Need to re-import the names referenced in ALL_PROMPTS — fix:
  const indexTs = [
    `// AUTO-GENERATED by scripts/sync-prompts.ts. Do not edit by hand.`,
    ``,
    ...generated.map((n) => `import { ${camelCase(n)}Prompt } from "./${n}.ts";`),
    ``,
    ...generated.map((n) => `export { ${camelCase(n)}Prompt };`),
    ``,
    `export const ALL_PROMPTS = [`,
    ...generated.map((n) => `  ${camelCase(n)}Prompt,`),
    `];`,
    ``,
  ].join("\n");
  await Deno.writeTextFile(join(PROMPTS_DIR, "index.ts"), indexTs);

  console.log(`\nDone. ${generated.length} prompt(s) synced: ${generated.join(", ")}`);
  console.log(`\nNext: deploy with \`supabase functions deploy ask-aster\`.`);
}

main();
